CREATE DATABASE YUMMYTUMMY;
SHOW DATABASES;
USE YUMMYTUMMY; # CONNECTING TO THE NEWLY CREATED DATABASE
SHOW TABLES; # TO SHOW ALL THE TABLES IN THE DATABASE

DROP TABLE  IF EXISTS IMAGES,RATINGS, IMAGEDESCRIPTION, MEALINGREDIENT, USERS, users;



CREATE TABLE IMAGES
(
  IMAGEID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  IMAGE BLOB NOT NULL,
  IMAGELABEL VARCHAR(30) NOT NULL
);

CREATE TABLE USERS
(
  userId  int(11) not null  auto_increment,
  userName varchar(60) not null,
  password varchar(20) not null,
PRIMARY KEY (userId)
);

CREATE TABLE RATINGS
(
  RATINGID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  RATING VARCHAR(255),
  IMAGEID INT NOT NULL,
  USERID INT NOT NULL,
  CONSTRAINT FOREIGN KEY (IMAGEID) REFERENCES IMAGES (IMAGEID),
  CONSTRAINT FOREIGN KEY (USERID) REFERENCES USERS (USERID)
);

CREATE TABLE IMAGEDESCRIPTION
(
    DESCID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    IMAGEID INT NOT NULL,
    DESCRIPTION VARCHAR (120),
	CONSTRAINT 	FOREIGN KEY (IMAGEID) REFERENCES IMAGES (IMAGEID)
	ON DELETE CASCADE
	ON UPDATE RESTRICT
);

CREATE TABLE MEALINGREDIENT
(
    INGREDIENTID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    IMAGEID INT NOT NULL,
    DESCRIPTION VARCHAR (255),
	CONSTRAINT 	FOREIGN KEY (IMAGEID) REFERENCES IMAGES (IMAGEID)
	ON DELETE CASCADE
	ON UPDATE RESTRICT
);
SHOW TABLES;
#HTTPS://GITHUB.COM/HADIDY100/YUMMYTUMMY.GIT
